# ---------------------------------------------------------------------------
# Vendored from https://github.com/eMobMarkus/evcc_simulator (commit c884950)
# -- the YFN x EU Energy Hackathon 2026 (EnBW track) reference EVCC connection
# stack, shared by the organizers as an example to build on. Incorporated into
# EVCC-SIFT-Mutator on 2026-09-27 to provide the real hardware/charger
# transport backend for the AI mutation harness.
#
# Only intra-package imports were adjusted (flat -> `connection.*`); the
# protocol logic is upstream's, verified against real charging-station
# hardware. Upstream carried no LICENSE file. See connection/README.md.
# ---------------------------------------------------------------------------

"""Direct CAN control of CP/PP simulation hardware on the test bench.

The two CAN frames used here were determined by comparing CAN trace
captures (deliberately flipping individual switches on the test bench and
observing the resulting frames on the "Analyser" bus). By sending these
same frames itself, this module takes over exactly the role that the test
bench's own control software would otherwise play for HLC initialization.

Known byte layout (from CAN trace comparison, not exhaustive -- only the
fields relevant to HLC session initialization have been verified):

0x0710 PilotGen_Config_710h (Tx, 8 bytes) -- CP signal generator:
    Byte0 Bit6 = TxActivate_Dev (0/1)
    Remaining bytes: baseline taken from the trace, not individually verified
    (TxPilotUpperLevel/TxPilotLowerLevel=120, TxPosPlateauLength_PilotGen=1000,
    TxPilotStatic_12V=1, all other fields=0 in every capture observed).

0x0510 LSA_EVSim_AND_PPEmulation_510h (Tx, 8 bytes) -- PP resistor emulation:
    Byte0 Bit0 = RxEV_Sim
    Byte1-2   = RxResistorR3 in ohms, big-endian uint16
    Byte3-4   = RxResistorR2 in ohms, big-endian uint16
    Byte5 Bit0 = RxResistorR3_on
    Byte5 Bit1 = RxResistorR2_on
    Byte5 Bit3 = PP_State
    Byte6-7   = unused (always 0x00 0x00 in every capture)

0x0500 LSA_EVSim_AND_PPEmulation_500h (Rx counterpart to 0x0510, same
byte layout per CanMessages.ini) -- does NOT come from the test bench
itself, but from the test system (the charging station/SECC side): its
actual feedback about what it sees/measures on the PP/CP line. It is
passively listened to by CanControl (parse_pp_evsim()), not sent by this
module. CanControl.set_pp_state_and_verify() uses this to wait, after
sending 0x0510, until 0x0500 confirms the same state (timeout ->
PPStateNotConfirmedError) -- so this is a genuine external confirmation
from the counterpart, not just a software loopback from the test bench.

0x0711 PilotGen_Response_711h (Rx counterpart to 0x0710) -- genuine
external confirmation from the test system, analyzed via 2 real captures
(Activate_Dev=0 and Activate_Dev=1): Byte0 mirrors TxActivate_Dev at the
same bit position (Byte0 Bit6 = RxActivate_Dev), i.e. the same
_set_bit()/_PILOT_GEN_ACTIVATE_DEV_* bit position used for the request.
The rest of the payload is not a byte-for-byte echo of the request --
Byte5 in particular differs (0x01 in every 0x0710 capture here vs 0x07 in
every 0x0711 capture here), most likely a hardware/firmware revision field
reported by the device (RxPilotGen_Hw_Rev per CanMessages.ini) rather than
anything activate_dev-dependent, so it is not used for verification.
set_pilot_gen_active_and_verify() waits for this confirmation the same way
set_pp_state_and_verify() does for 0x0500; set_pilot_gen_active() itself
remains fire-and-forget.

0x0100 PWMDetector_100h_EV / 0x0150 PWMDetector_150h_EVSE (Rx, 8 bytes,
bit-identical to each other) -- CP level/state as actually measured by the
test system. Bit layout determined by CAN trace comparison (3 real CP
states A1/B2/C1) AND cross-validated against the (startBit, length,
signed, offset, factor) tuples obtained via .NET IL analysis of CAN.dll --
not by pure guesswork:
    Bit 59, length 4            = PlatLvlCode (CP state code: A=6, B=5, C=4;
                                   D/E/F are NOT backed by real samples,
                                   only linearly extrapolated -- see
                                   CP_STATE_LETTERS)
    Bit 23, length 12, signed   = VoltageMeas_ADC (CP high-level voltage,
                                   factor 0.01) -- exact match in all
                                   5 samples (deviations <0.15V are normal
                                   ADC noise)
    Bit 63, length 4            = VoltageMeas_ADC_NEG_PLAT (offset -10.0,
                                   factor -0.2)
    Bit 15, length 1            = PWMmultiplexer (0 in every sample)

    PWM duty cycle (pulse_100ns/pause_100ns) -- IMPORTANT: generated by the
    real charging station (EVSE side), not by this script/the EV
    simulation; we only read it out to know when the counterpart signals
    the 5% duty cycle ("Digital Communication Mode requested", DIN SPEC
    70121). The bit positions suggested by the IL (bit 45/27, "Branch A",
    length 14) were WRONG -- they contradicted the zero-duty-cycle
    samples. Re-derived empirically from 7 real captures (0%, 4.9%, 5.1%,
    each for the EV/EVSE side), using a DIFFERENT bit convention than the
    other fields of this message (big-endian 64-bit word instead of
    little-endian -- see _extract_bits_be()):
    Bit 31, length 10, big-endian = pulse_100ns (factor 0.1)
    Bit 21, length 14, big-endian = pause_100ns (factor 0.1)
    duty_cycle_percent = pulse_100ns / (pulse_100ns + pause_100ns) * 100
    Exact match (including the computed duty cycle) in all 7 samples.

0x01F0 ComFrame_KeepAlive (Tx, periodic every 25ms, name assigned by the
vendor per CanMessages.ini):
    Present in every capture right from the start of the session -- the
    test bench presumably expects an ongoing heartbeat on the bus,
    otherwise it falls back into a fallback/error state and the CP/PP
    values set above lose their effect. Byte7 differs between captures
    (0xEE/0x33/0x44/0xBB/0x22/0x00) -- presumably a free-running
    counter/session identifier, NOT determined empirically as an algorithm
    (only a single snapshot per session is available, no follow-up
    frames). This implementation increments Byte7 on every send starting
    from 0 -- if the test bench expects a specific value/checksum, that
    still needs to be verified empirically (e.g. by capturing several
    consecutive KeepAlive frames).
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass

logger = logging.getLogger(__name__)

PP_STATE_VERIFY_TIMEOUT_S = 1.0
PP_STATE_VERIFY_POLL_INTERVAL_S = 0.05
PILOT_GEN_VERIFY_TIMEOUT_S = 1.0
PILOT_GEN_VERIFY_POLL_INTERVAL_S = 0.05

# CP state B with ~5% duty cycle = "Digital Communication Mode requested"
# per DIN SPEC 70121 -- see README.md "CP state sequence for establishing
# the HLC session". Tolerance of +-1% to cover measurement/rounding noise.
HLC_REQUEST_DUTY_CYCLE_MIN = 4.0
HLC_REQUEST_DUTY_CYCLE_MAX = 6.0
# Textbook expectation is state B (see README table). On real DC charging
# station hardware, however, the 5% request has been observed to already
# be reported in state C -- C is therefore additionally tolerated.
HLC_REQUEST_ACCEPTED_CP_STATES = {"B", "C"}
CP_STATE_WAIT_TIMEOUT_S = 10.0
CP_STATE_WAIT_POLL_INTERVAL_S = 0.1


class PPStateNotConfirmedError(RuntimeError):
    """0x0510 was sent, but the 0x0500 feedback from the test system
    (charging station/SECC side) does not confirm the desired state
    within the timeout."""


class CpHlcRequestNotDetectedError(RuntimeError):
    """The charging station did not report a CP state B with ~5% duty
    cycle (HLC request per DIN SPEC 70121) within the timeout -- see
    get_cp_level()/0x0100/0x0150."""


class PilotGenNotConfirmedError(RuntimeError):
    """0x0710 was sent, but the 0x0711 feedback from the test system does
    not confirm the requested Activate_Dev state within the timeout."""


PILOT_GEN_CONFIG_ID = 0x0710
PILOT_GEN_RESPONSE_ID = 0x0711
PP_EVSIM_ID = 0x0510
PP_EVSIM_FEEDBACK_ID = 0x0500
PWM_DETECTOR_EV_ID = 0x0100
PWM_DETECTOR_EVSE_ID = 0x0150
KEEP_ALIVE_ID = 0x01F0
KEEP_ALIVE_PERIOD_S = 0.025
FEEDBACK_RECV_TIMEOUT_S = 0.1

# Empirically observed (with an incorrectly configured bitrate): "CAN form
# error"/"CAN bit stuff error" pile up until the Ixxat driver falls into
# the error-warning state (VCIError "Error warning limit exceeded" on
# EVERY subsequent recv(), see canlib_vcinpl.py -- this state does NOT
# resolve on its own; the controller's error counter only decreases
# through actually successful frames). Instead of just logging this
# endlessly, the feedback listener attempts to reinitialize the channel
# itself after a few consecutive errors (close+reopen).
CAN_ERROR_RECOVERY_CONSECUTIVE_THRESHOLD = 5
CAN_ERROR_RECOVERY_MAX_ATTEMPTS = 5
CAN_ERROR_RECOVERY_SETTLE_S = 0.3

# PlatLvlCode -> CP state letter. Only A/B/C are backed by real samples
# (A1/B2/C1 captures); D/E/F are purely linearly extrapolated (pattern
# "code = 6 - state_index") and NOT verified.
CP_STATE_LETTERS = {6: "A", 5: "B", 4: "C", 3: "D", 2: "E", 1: "F"}

_PILOT_GEN_BASELINE = bytearray.fromhex("0227100000017878")
_PILOT_GEN_ACTIVATE_DEV_BYTE = 0
_PILOT_GEN_ACTIVATE_DEV_BIT = 6

_PP_EVSIM_EV_SIM_BYTE = 0
_PP_EVSIM_EV_SIM_BIT = 0
_PP_EVSIM_R3_ON_BIT = 0
_PP_EVSIM_R2_ON_BIT = 1
_PP_EVSIM_PP_STATE_BIT = 3


def _set_bit(value: int, bit: int, on: bool) -> int:
    if on:
        return value | (1 << bit)
    return value & ~(1 << bit)


def build_pilot_gen_config(activate_dev: bool) -> bytes:
    payload = bytearray(_PILOT_GEN_BASELINE)
    payload[_PILOT_GEN_ACTIVATE_DEV_BYTE] = _set_bit(
        payload[_PILOT_GEN_ACTIVATE_DEV_BYTE], _PILOT_GEN_ACTIVATE_DEV_BIT, activate_dev
    )
    return bytes(payload)


def parse_pilot_gen_response(data: bytes) -> dict:
    """Decodes 0x0711 (PilotGen_Response_711h) -- see the module docstring
    for the CAN trace analysis this is based on. Only `activate_dev` is
    used for verification (set_pilot_gen_active_and_verify()); `hw_rev`
    is informational (the low byte of Byte5, e.g. 7 on the real hardware
    this was captured against), not activate_dev-dependent."""
    return {
        "activate_dev": bool(data[_PILOT_GEN_ACTIVATE_DEV_BYTE] & (1 << _PILOT_GEN_ACTIVATE_DEV_BIT)),
        "hw_rev": data[5],
    }


def build_keep_alive(counter: int) -> bytes:
    payload = bytearray(8)
    payload[7] = counter & 0xFF
    return bytes(payload)


def build_pp_evsim(
    r2_ohm: int,
    r3_ohm: int,
    r2_on: bool,
    r3_on: bool,
    pp_state: bool,
    ev_sim: bool = True,
) -> bytes:
    if not 0 <= r2_ohm <= 0xFFFF:
        raise ValueError(f"r2_ohm out of range: {r2_ohm}")
    if not 0 <= r3_ohm <= 0xFFFF:
        raise ValueError(f"r3_ohm out of range: {r3_ohm}")

    payload = bytearray(8)
    payload[0] = _set_bit(payload[0], _PP_EVSIM_EV_SIM_BIT, ev_sim)
    payload[1] = (r3_ohm >> 8) & 0xFF
    payload[2] = r3_ohm & 0xFF
    payload[3] = (r2_ohm >> 8) & 0xFF
    payload[4] = r2_ohm & 0xFF
    payload[5] = _set_bit(payload[5], _PP_EVSIM_R3_ON_BIT, r3_on)
    payload[5] = _set_bit(payload[5], _PP_EVSIM_R2_ON_BIT, r2_on)
    payload[5] = _set_bit(payload[5], _PP_EVSIM_PP_STATE_BIT, pp_state)
    return bytes(payload)


def parse_pp_evsim(data: bytes) -> dict:
    """Inverse of build_pp_evsim() -- decodes 0x0500/0x0510 payloads."""
    byte0, byte1, byte2, byte3, byte4, byte5 = data[0], data[1], data[2], data[3], data[4], data[5]
    return {
        "ev_sim": bool(byte0 & (1 << _PP_EVSIM_EV_SIM_BIT)),
        "r3_ohm": (byte1 << 8) | byte2,
        "r2_ohm": (byte3 << 8) | byte4,
        "r3_on": bool(byte5 & (1 << _PP_EVSIM_R3_ON_BIT)),
        "r2_on": bool(byte5 & (1 << _PP_EVSIM_R2_ON_BIT)),
        "pp_state": bool(byte5 & (1 << _PP_EVSIM_PP_STATE_BIT)),
    }


def _extract_bits(data: bytes, start_bit: int, length: int, signed: bool = False) -> int:
    """DBC-Motorola-style bit extraction, as used by CanMessages.ini:
    start_bit is the MSB of the field, counted from the LSB of the first
    byte (Byte0) onward (little-endian 64-bit word). Verified against real
    CP1/CP2 samples for 0x0100/0x0150, see module docstring."""
    word = int.from_bytes(data, "little")
    shift = start_bit - length + 1
    raw = (word >> shift) & ((1 << length) - 1)
    if signed and raw & (1 << (length - 1)):
        raw -= 1 << length
    return raw


def _extract_bits_be(data: bytes, start_bit: int, length: int) -> int:
    """Like _extract_bits(), but with a big-endian 64-bit word (Byte0 =
    MSB) -- only applies to pulse_100ns/pause_100ns in 0x0100/0x0150, see
    module docstring for the empirical derivation."""
    word = int.from_bytes(data, "big")
    shift = start_bit - length + 1
    return (word >> shift) & ((1 << length) - 1)


def parse_cp_level(data: bytes) -> dict:
    """Decodes 0x0100 (PWMDetector_100h_EV) / 0x0150 (PWMDetector_150h_EVSE)
    -- CP state code, CP voltage level, and PWM duty cycle, as measured/
    generated by the test system (the real charging station)."""
    plat_lvl_code = _extract_bits(data, 59, 4)
    pulse_100ns = _extract_bits_be(data, 31, 10) * 0.1
    pause_100ns = _extract_bits_be(data, 21, 14) * 0.1
    total = pulse_100ns + pause_100ns
    return {
        "plat_lvl_code": plat_lvl_code,
        "cp_state": CP_STATE_LETTERS.get(plat_lvl_code),
        "voltage_meas_adc": _extract_bits(data, 23, 12, signed=True) * 0.01,
        "voltage_meas_adc_neg_plat": _extract_bits(data, 63, 4) * -0.2 + -10.0,
        "pwm_multiplexer": _extract_bits(data, 15, 1),
        "pulse_100ns": pulse_100ns,
        "pause_100ns": pause_100ns,
        "duty_cycle_percent": (pulse_100ns / total * 100.0) if total > 0 else 0.0,
    }


def list_available_channels(bustype: str = "ixxat") -> list[dict]:
    """Lists the CAN channels recognized by the python-can backend.

    An ixxat adapter can have multiple physical CAN channels (e.g. on the
    "professional" series) -- which one is actually connected to the test
    bench's "Analyser" bus has to be determined once (choosing the wrong
    channel leads to "Transmit queue full", since nobody acknowledges the
    frames). Only works if the backend supports enumeration -- if not,
    determine the channel instead via Ixxat's own "VCI Device Manager" and
    enter it in CanConfig.channel.
    """
    import can

    try:
        return can.detect_available_configs(interfaces=[bustype])
    except Exception:
        logger.exception("Channel detection for bustype=%s failed.", bustype)
        return []


def query_bus_status(can_ctrl: "CanControl") -> dict | None:
    """Queries canControlGetStatus()/canChannelGetStatus() directly
    (beyond what python-can's public API/BusState exposes) --
    in particular bBusLoad (average bus load in %), to distinguish
    whether the bus is completely inactive (0% load, nothing going on
    electrically/physically) or active but only occupied with errors
    (high load despite 0 valid frames received) -- two fundamentally
    different failure causes. Best-effort: returns None if unavailable
    (e.g. a different backend, or in tests with a fake bus). Only
    implemented for the Ixxat backend (can_ctrl._bus.bus with VCI3
    handles)."""
    try:
        import ctypes

        import can.interfaces.ixxat.canlib_vcinpl as vcinpl
        from can.interfaces.ixxat import structures

        inner = can_ctrl._bus.bus  # can.interfaces.ixxat.canlib.IXXATBus wraps canlib_vcinpl.IXXATBus
        line_status = structures.CANLINESTATUS()
        vcinpl._canlib.canControlGetStatus(inner._control_handle, ctypes.byref(line_status))
        chan_status = structures.CANCHANSTATUS()
        vcinpl._canlib.canChannelGetStatus(inner._channel_handle, ctypes.byref(chan_status))
        return {
            "opmode": hex(line_status.bOpMode),
            "btr0": hex(line_status.bBtReg0),
            "btr1": hex(line_status.bBtReg1),
            "bus_load_percent": line_status.bBusLoad,
            "status_flags": hex(line_status.dwStatus),
            "channel_activated": bool(chan_status.fActivated),
            "rx_overrun": bool(chan_status.fRxOverrun),
            "rx_fifo_load_percent": chan_status.bRxFifoLoad,
        }
    except Exception:
        logger.exception("Bus status (canControlGetStatus/canChannelGetStatus) not available.")
        return None


@dataclass
class CanControlConfig:
    channel: int = 0
    bustype: str = "ixxat"
    # See config.py::CanConfig.bitrate comment: empirically confirmed
    # 1000000, not 500000.
    bitrate: int = 1_000_000


class CanControl:
    """Sends CP/PP control frames directly on the Analyser CAN bus."""

    def __init__(self, cfg: CanControlConfig | None = None):
        self.cfg = cfg or CanControlConfig()
        self._bus = None
        self._keep_alive_thread = None
        self._keep_alive_stop = None
        self._feedback_thread = None
        self._feedback_stop = None
        self._feedback_lock = None
        self._latest_pp_feedback: dict | None = None
        self._latest_cp_level_ev: dict | None = None
        self._latest_cp_level_evse: dict | None = None
        self._latest_pilot_gen_feedback: dict | None = None

    def connect(self) -> None:
        import can

        self._bus = can.interface.Bus(
            channel=self.cfg.channel, bustype=self.cfg.bustype, bitrate=self.cfg.bitrate
        )

    def _reinit_bus(self) -> bool:
        """Attempts to reinitialize the CAN channel (close + reopen) --
        a self-healing attempt for the case where the Ixxat driver has
        fallen into the error-warning/error-passive state (see comment on
        CAN_ERROR_RECOVERY_*). Best-effort: catches all errors and only
        returns True/False, never raises itself."""
        import can

        logger.info("Attempting to reinitialize the CAN channel (channel=%s)...", self.cfg.channel)
        if self._bus is not None:
            try:
                self._bus.shutdown()
            except Exception:
                logger.exception("Old CAN bus handle could not be closed cleanly.")
            self._bus = None
        time.sleep(CAN_ERROR_RECOVERY_SETTLE_S)
        try:
            self._bus = can.interface.Bus(
                channel=self.cfg.channel, bustype=self.cfg.bustype, bitrate=self.cfg.bitrate
            )
        except Exception:
            logger.exception("CAN channel reinitialization failed.")
            return False
        logger.info("CAN channel reinitialized.")
        return True

    def close(self) -> None:
        self.teardown()
        self.stop_keep_alive()
        self.stop_feedback_listener()
        if self._bus is not None:
            self._bus.shutdown()
            self._bus = None

    def teardown(self) -> None:
        """Brings the CP/PP hardware into a safe idle state -- called
        automatically by close() (on success AND on failure, see
        main.py/manual_control.py: both call close() in a finally block).
        Best-effort: catches all errors and NEVER raises an exception
        itself, so teardown still runs through even if the bus is already
        unstable or the original exception must not be masked."""
        if self._bus is None:
            return
        try:
            self.set_pilot_gen_active(False)
        except Exception:
            logger.exception("Teardown: Activate_Dev could not be deactivated.")
        try:
            self.set_pp_state(r2_ohm=0, r3_ohm=0, r2_on=False, r3_on=False, pp_state=False, ev_sim=False)
        except Exception:
            logger.exception("Teardown: PP/EVSim state could not be reset.")

    def start_keep_alive(self) -> None:
        import threading

        assert self._bus is not None, "call connect() first"
        if self._keep_alive_thread is not None:
            return
        self._keep_alive_stop = threading.Event()
        stop_event = self._keep_alive_stop

        def _loop() -> None:
            counter = 0
            while not stop_event.is_set():
                try:
                    self._send(KEEP_ALIVE_ID, build_keep_alive(counter))
                except Exception:
                    logger.exception(
                        "ComFrame_KeepAlive frame could not be sent "
                        "(e.g. bus without ACK) -- keep-alive continues running."
                    )
                counter = (counter + 1) & 0xFF
                stop_event.wait(KEEP_ALIVE_PERIOD_S)

        self._keep_alive_thread = threading.Thread(target=_loop, daemon=True)
        self._keep_alive_thread.start()

    def stop_keep_alive(self) -> None:
        if self._keep_alive_thread is not None:
            self._keep_alive_stop.set()
            self._keep_alive_thread.join(timeout=1.0)
            self._keep_alive_thread = None
            self._keep_alive_stop = None

    def start_feedback_listener(self) -> None:
        import threading

        assert self._bus is not None, "call connect() first"
        if self._feedback_thread is not None:
            return
        self._feedback_lock = threading.Lock()
        self._feedback_stop = threading.Event()
        stop_event = self._feedback_stop

        def _loop() -> None:
            consecutive_errors = 0
            recovery_attempts = 0
            while not stop_event.is_set():
                try:
                    msg = self._bus.recv(timeout=FEEDBACK_RECV_TIMEOUT_S)
                except Exception:
                    consecutive_errors += 1
                    logger.exception(
                        "Receiving on the CAN bus failed (%s x in a row) -- "
                        "feedback listener continues running.",
                        consecutive_errors,
                    )
                    if (
                        consecutive_errors >= CAN_ERROR_RECOVERY_CONSECUTIVE_THRESHOLD
                        and recovery_attempts < CAN_ERROR_RECOVERY_MAX_ATTEMPTS
                    ):
                        recovery_attempts += 1
                        logger.warning(
                            "Repeated CAN bus errors -- attempting self-healing "
                            "(attempt %s/%s).",
                            recovery_attempts, CAN_ERROR_RECOVERY_MAX_ATTEMPTS,
                        )
                        if self._reinit_bus():
                            consecutive_errors = 0
                    else:
                        stop_event.wait(FEEDBACK_RECV_TIMEOUT_S)
                    continue
                consecutive_errors = 0
                recovery_attempts = 0
                if msg is None:
                    continue
                if msg.arbitration_id == PP_EVSIM_FEEDBACK_ID:
                    parsed = parse_pp_evsim(bytes(msg.data))
                    with self._feedback_lock:
                        self._latest_pp_feedback = parsed
                elif msg.arbitration_id == PWM_DETECTOR_EV_ID:
                    parsed = parse_cp_level(bytes(msg.data))
                    with self._feedback_lock:
                        self._latest_cp_level_ev = parsed
                elif msg.arbitration_id == PWM_DETECTOR_EVSE_ID:
                    parsed = parse_cp_level(bytes(msg.data))
                    with self._feedback_lock:
                        self._latest_cp_level_evse = parsed
                elif msg.arbitration_id == PILOT_GEN_RESPONSE_ID:
                    parsed = parse_pilot_gen_response(bytes(msg.data))
                    with self._feedback_lock:
                        self._latest_pilot_gen_feedback = parsed

        self._feedback_thread = threading.Thread(target=_loop, daemon=True)
        self._feedback_thread.start()

    def stop_feedback_listener(self) -> None:
        if self._feedback_thread is not None:
            self._feedback_stop.set()
            self._feedback_thread.join(timeout=1.0)
            self._feedback_thread = None
            self._feedback_stop = None
            self._feedback_lock = None

    def get_pp_feedback(self) -> dict | None:
        """Most recently received actual state from 0x0500 (from the test
        system/the charging station, not from the test bench itself), or
        None if no feedback has been received yet."""
        if self._feedback_lock is None:
            return self._latest_pp_feedback
        with self._feedback_lock:
            return self._latest_pp_feedback

    def get_pilot_gen_feedback(self) -> dict | None:
        """Most recently received actual state from 0x0711 (from the test
        system, not from the test bench itself), or None if no feedback
        has been received yet. See parse_pilot_gen_response()."""
        if self._feedback_lock is None:
            return self._latest_pilot_gen_feedback
        with self._feedback_lock:
            return self._latest_pilot_gen_feedback

    def get_cp_level(self, side: str = "ev") -> dict | None:
        """Most recently received CP state/level (including duty cycle)
        from 0x0100 (side='ev') or 0x0150 (side='evse'), or None if no
        feedback has been received yet. See parse_cp_level()."""
        attr = "_latest_cp_level_ev" if side == "ev" else "_latest_cp_level_evse"
        if self._feedback_lock is None:
            return getattr(self, attr)
        with self._feedback_lock:
            return getattr(self, attr)

    def wait_for_hlc_request(
        self,
        side: str = "ev",
        timeout_s: float = CP_STATE_WAIT_TIMEOUT_S,
        poll_interval_s: float = CP_STATE_WAIT_POLL_INTERVAL_S,
    ) -> dict:
        """Waits until the charging station (test system) reports CP
        state B **or** C with a duty cycle in the 4-6% range -- the
        standardized "Digital Communication Mode requested" signal per
        DIN SPEC 70121 (see README.md "CP state sequence for establishing
        the HLC session"). Textbook expectation is state B; state C is
        additionally tolerated because this has been observed on at least
        one real DC charging station (see README). Requires
        start_feedback_listener() to have been called. Returns the
        confirming CP level snapshot; raises CpHlcRequestNotDetectedError
        on timeout."""
        deadline = time.monotonic() + timeout_s
        last = None
        while time.monotonic() < deadline:
            last = self.get_cp_level(side)
            if (
                last is not None
                and last.get("cp_state") in HLC_REQUEST_ACCEPTED_CP_STATES
                and HLC_REQUEST_DUTY_CYCLE_MIN <= last.get("duty_cycle_percent", -1.0) <= HLC_REQUEST_DUTY_CYCLE_MAX
            ):
                return last
            time.sleep(poll_interval_s)
        raise CpHlcRequestNotDetectedError(
            f"No CP state in {sorted(HLC_REQUEST_ACCEPTED_CP_STATES)} with duty cycle in range "
            f"{HLC_REQUEST_DUTY_CYCLE_MIN}-{HLC_REQUEST_DUTY_CYCLE_MAX}% "
            f"detected within {timeout_s}s (side={side!r}); "
            f"last received: {last}"
        )

    def _send(self, arbitration_id: int, data: bytes, timeout: float | None = None) -> None:
        """timeout=None (default): python-can's Ixxat backend uses
        canChannelPostMessage() for this -- it only enqueues the frame in
        the local send queue and returns immediately, WITHOUT waiting for
        an actual bus acknowledgement (ACK). A supplied timeout instead
        uses canChannelSendMessage(), which waits up to timeout seconds for
        the actual send confirmation -- only this lets you check whether a
        frame actually arrived on the bus, rather than just being accepted
        locally."""
        import can

        assert self._bus is not None, "call connect() first"
        msg = can.Message(arbitration_id=arbitration_id, data=data, is_extended_id=False)
        self._bus.send(msg, timeout=timeout)

    def set_pilot_gen_active(self, activate_dev: bool) -> None:
        self._send(PILOT_GEN_CONFIG_ID, build_pilot_gen_config(activate_dev))

    def set_pilot_gen_active_and_verify(
        self,
        activate_dev: bool,
        timeout_s: float = PILOT_GEN_VERIFY_TIMEOUT_S,
        poll_interval_s: float = PILOT_GEN_VERIFY_POLL_INTERVAL_S,
    ) -> dict:
        """Like set_pilot_gen_active(), but afterwards waits for a 0x0711
        feedback from the test system that confirms the requested
        Activate_Dev state (requires start_feedback_listener() to have
        been called). Returns the confirming feedback; raises
        PilotGenNotConfirmedError if no matching feedback arrives within
        timeout_s."""
        self.set_pilot_gen_active(activate_dev)
        deadline = time.monotonic() + timeout_s
        while time.monotonic() < deadline:
            feedback = self.get_pilot_gen_feedback()
            if feedback is not None and feedback["activate_dev"] == activate_dev:
                return feedback
            time.sleep(poll_interval_s)
        raise PilotGenNotConfirmedError(
            f"Test system did not confirm the requested Activate_Dev state: "
            f"expected {activate_dev}, last received {self.get_pilot_gen_feedback()}"
        )

    def set_pp_state(
        self,
        r2_ohm: int,
        r3_ohm: int,
        r2_on: bool,
        r3_on: bool,
        pp_state: bool,
        ev_sim: bool = True,
    ) -> None:
        self._send(
            PP_EVSIM_ID,
            build_pp_evsim(r2_ohm, r3_ohm, r2_on, r3_on, pp_state, ev_sim),
        )

    def set_pp_state_and_verify(
        self,
        r2_ohm: int,
        r3_ohm: int,
        r2_on: bool,
        r3_on: bool,
        pp_state: bool,
        ev_sim: bool = True,
        timeout_s: float = PP_STATE_VERIFY_TIMEOUT_S,
        poll_interval_s: float = PP_STATE_VERIFY_POLL_INTERVAL_S,
    ) -> dict:
        """Like set_pp_state(), but afterwards waits for a 0x0500 feedback
        from the test system (charging station/SECC side, not from the
        test bench itself) that confirms the sent state (requires
        start_feedback_listener() to have been called). Returns the
        confirming feedback; raises PPStateNotConfirmedError if no
        matching feedback arrives within timeout_s (e.g. the switch did
        not close)."""
        self.set_pp_state(r2_ohm, r3_ohm, r2_on, r3_on, pp_state, ev_sim)
        expected = {
            "ev_sim": ev_sim,
            "r2_ohm": r2_ohm,
            "r3_ohm": r3_ohm,
            "r2_on": r2_on,
            "r3_on": r3_on,
            "pp_state": pp_state,
        }
        deadline = time.monotonic() + timeout_s
        while time.monotonic() < deadline:
            feedback = self.get_pp_feedback()
            if feedback == expected:
                return feedback
            time.sleep(poll_interval_s)
        raise PPStateNotConfirmedError(
            f"Test system did not confirm the sent PP/EVSim state: "
            f"expected {expected}, last received {self.get_pp_feedback()}"
        )
